### ISSUE TITLE
Container keeps exiting

### ISSUE THREAD

**Issue by drallgood** [burntcookie90/librofm-downloader#17]
Running the docker container, it seems to download a few files then exit.

Nothing really in the logs that would indicate an error. All I see is:
```
librofm-downloader-1  | 2024-12-27 01:47:41.684 [main] TRACE i.k.c.plugins.HttpRequestLifecycle - Cancelling request because engine Job completed
librofm-downloader-1  | Exception in thread "main" kotlinx.coroutines.JobCancellationException: Parent job is Completed; job=SupervisorJobImpl{Completed}@644abb8fg
```

**Comment by burntcookie90** [comment]
could you enable `VERBOSE` logging and see what it spits out?

**Comment by drallgood** [comment]
yeah.. just tried that. Unfortunately since it also outputs the binary content it's a bit hard to read :D 
The issue does not occur in "dry run" mode. I suspect some error gets thrown but then is swallowed by Kotlin.. but can't confirm that

**Comment by burntcookie90** [comment]
just to confirm: are you running this via docker-compose? I dont think it'll change anything but just interested in the run environment

**Comment by drallgood** [comment]
@burntcookie90 Indeed I am.

**Comment by burntcookie90** [comment]
i'll try and poke around and see what i can come up, even if its something to help log better.

**Comment by burntcookie90** [comment]
ive pushed a few changes to the container, feel free to pull `main` or `latest` and see if its maybe fixed by side effect? 😅

**Comment by drallgood** [comment]
Unfortunately not. @burntcookie90 
But you never know.. was worth a try 😄

**Comment by burntcookie90** [comment]
Darn. My one last request would be to try and run it with a new data directory bind so that it can start clean. Otherwise I'll try and get a custom image up with some better/smarter logging to try and debug a bit in the new year.

**Comment by drallgood** [comment]
Tried that already but I just did it again just in case... no luck. 
Smarter logging sounds like a good idea. Thanks for the efforts!!!

**Comment by drallgood** [comment]
I found the issue!!
My Kotlin was a bit... rusty... but when debugging I noticed that it would ALWAYS fail after the first book (whereas when running it standalone it was a bit random when exactly would fail). 

After a bit of randomly peaking and poking at things (at first I thought it was an exception that cancelled the main thread.. then I thought it was a concurrency issue of some sort) I realized that the HTTPClient was "closed" from there I read up on the http client and bingo! 
it's this line: https://github.com/burntcookie90/librofm-downloader/blob/d80da0d83e7256c171f64693380d010b33f46154/server/src/main/kotlin/com/vishnurajeevan/libroabs/libro/LibroFmClient.kt#L88

`httpClient.use{}` autocloses the http client which then fails when reused!
See https://ktor.io/docs/client-create-and-configure.html#close-client

**Comment by burntcookie90** [comment]
Oh wow, thanks for digging! I'll have sometime mid week to try and make some fixes. I wonder why I hadn't run into this

**Comment by burntcookie90** [comment]
#25 might be related as well

**Comment by burntcookie90** [comment]
can you try and pull from the `main` tag and lemme know if its working on your end? I'll cut a new release after so `latest` can be updated

**Comment by drallgood** [comment]
Wow.. that was quick! @burntcookie90 
Works. I was able to download my entire library (started from a clean state just to be safe) and now the webserver is running. 
Tested the /update endpoint and it works too without crashing

**Comment by burntcookie90** [comment]
Fantastic! Thanks again for locating the bug, saved me a bunch of time.

**Comment by drallgood** [comment]
You're welcome. Thank you for the project. Saved me a bunch of time too 😆
